spring.application.name=blue
spring.datasource.url=jdbc:mysql://localhost:3306/blue_db
spring.datasource.username=root
spring.datasource.password=harinipallepati@9806

spring.jpa.hibernate.ddl-auto=update
sprig.jpa.show-sql=true
